# Generated by Django 6.0 on 2025-12-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('profile_picture', models.ImageField(upload_to='profile_pics/')),
                ('skills', models.CharField(max_length=255)),
                ('dob', models.DateField()),
            ],
        ),
    ]
