# Generated by Django 6.0 on 2025-12-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.CharField(help_text='Comma separated skills', max_length=255),
        ),
    ]
