# Generated by Django 6.0 on 2026-01-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('taste', models.CharField(choices=[('Sweet', 'Sweet'), ('Sour', 'Sour'), ('Bitter', 'Bitter'), ('Salty', 'Salty'), ('Umami', 'Umami')], default='Sweet', max_length=10)),
                ('alcohol_content', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mfg_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
